### ISSUE TITLE
Question about Firefox

### ISSUE THREAD

**Issue by Srini-B** [sindresorhus/get-windows#153] opened 2022-11-23 04:34 UTC
Hi, can anyone confirm me if URLs from Firefox are captured, It doesn't work for me. I also have userchrome.css enabled which modifies the UI, maybe it's the cause. I'm on macOS 13.0.1

**Comment by anis-dr** [comment] 2023-07-13 17:20
I'm having the same issue, URLs are not captured from Firefox

**Comment by vojtabohm** [comment] 2024-07-12 17:04
This is because it does not work with the approach this library uses (which is to use AppleScript to 'tell' the browser to return it's url). I solved this a while ago on my macOS project. You can actually use Accessibility API to get it.

1. You need to set `AXManualAccessibility` on the Firefox process, which will enable it's DOM to be visible (this property tells the app a 'Screen reader' is present on the screen, so this is a sort of a hack).
2. Traverse the Firefox's DOM (consisting of AXUIElement) using BFS until you find a node that has a `url` attribute and read that.

It's a hassle to add this, but unfortunately, no better way to do this for Firefox. I read their forums a while back.

**Comment by sindresorhus** [comment] 2024-08-09 23:05
Duplicate of #172

**Closed by sindresorhus** 2024-08-09 23:05 UTC
